name: Chassis
version: 1.5.0
authors: Connor Sears
description: A lightweight HTML & CSS base layer for mobile-first web development
url: http://connors.github.io/chassis

# Permalinks
permalink: pretty